import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hart Portoflio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="bg-slate-600 ">
          <h1 className="text-3xl font-bold underline">Hello world!</h1>
        </section>
      </main>
    </div>
  );
}
